---
default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json # Checks json files for parseable syntax.
        files: "^.*.json$"
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-vcs-permalinks
      - id: detect-private-key # Checks for the existence of private keys.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: file-contents-sorter
        files: .gitignore|.markdownlintignore|.prettierignore
      - id: sort-simple-yaml
      - id: trailing-whitespace # This hook trims trailing whitespace.

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        files: "^.*.json5$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        stages: [pre-commit]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.39.0"
    hooks:
      - id: markdownlint
        stages: [pre-commit]
        args:
          - --config=.markdownlint.yaml

  - repo: local
    hooks:
      - id: renovate-config-validator
        name: renovate-config-validator
        entry: make renovate-config-validator
        language: system
